Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load image
im = load_image('spooked.png')

# Re-save as a JPEG; we do need to set the JPEG compression quite low to make the artefacts obvious
from imageio import imread, imwrite
bytes_jpg = imwrite("<bytes>", im, plugin='pillow', format="JPEG", quality=20)
im_jpg = imread(bytes_jpg)

# Re-save as a PNG
bytes_png = imwrite("<bytes>", im, format="PNG")
im_png = imread(bytes_png)

# Re-save as an uncompressed TIFF
bytes_tif = imwrite("<bytes>", im, format="TIFF")
im_tif = imread(bytes_tif)

def add_rectangle(x, y, width, height, axes=None, linewidth=1, edgecolor='r', facecolor='none', **kwargs):
    """
    Add rectangle to highlight selected region.
    """
    import matplotlib.patches as patches
    rect = patches.Rectangle((x, y), width, height, linewidth=1, edgecolor='r', facecolor='none')
    if axes is None:
        axes = plt.gca()
    axes.add_patch(rect)

# Show image & details
fig = create_figure(figsize=(9, 5))
show_image(im_tif, pos=231, title=f'(A) TIFF uncompressed ({len(bytes_tif)/1024.0:.1f} KB)')
show_image(im_png, pos=232, title=f'(B) PNG compressed ({len(bytes_png)/1024.0:.1f} KB)')
show_image(im_jpg, pos=233, title=f'(C) JPEG compressed ({len(bytes_jpg)/1024.0:.1f} KB)')

r = 200
c = 200
w = 50
h = 38
show_image(im_tif[r:r+h, c:c+w], pos=234)
show_image(im_png[r:r+h, c:c+w], pos=235)
show_image(im_jpg[r:r+h, c:c+w], pos=236)

# Add rectangle to highlight detail area
for ax in fig.axes:
    add_rectangle(c, r, w, h, axes=ax)


plt.tight_layout()
glue_fig('fig_files_lossy', fig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/plugins/tifffile.py:488[0m, in [0;36mTiffFormat.Writer._open[0;34m(self, bigtiff, byteorder, software)[0m
[1;32m    487[0m [38;5;28;01mtry[39;00m:
[0;32m--> 488[0m     [38;5;28mself[39m[38;5;241m.[39m_tf [38;5;241m=[39m [43m_tifffile[49m[38;5;241;43m.[39;49m[43mTiffWriter[49m[43m([49m
[1;32m    489[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mget_file[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mbigtiff[49m[43m,[49m[43m [49m[43mbyteorder[49m[43m,[49m[43m [49m[43msoftware[49m[38;5;241;43m=[39;49m[43msoftware[49m
[1;32m    490[0m [43m    [49m[43m)[49m
[1;32m    491[0m     [38;5;28mself[39m[38;5;241m.[39m_software [38;5;241m=[39m [38;5;28;01mNone[39;00m

[0;31mTypeError[0m: TiffWriter.__init__() got an unexpected keyword argument 'software'

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 14>[0;34m()[0m
[1;32m     11[0m im_png [38;5;241m=[39m imread(bytes_png)
[1;32m     13[0m [38;5;66;03m# Re-save as an uncompressed TIFF[39;00m
[0;32m---> 14[0m bytes_tif [38;5;241m=[39m [43mimwrite[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m<bytes>[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mim[49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mTIFF[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     15[0m im_tif [38;5;241m=[39m imread(bytes_tif)
[1;32m     17[0m [38;5;28;01mdef[39;00m [38;5;21madd_rectangle[39m(x, y, width, height, axes[38;5;241m=[39m[38;5;28;01mNone[39;00m, linewidth[38;5;241m=[39m[38;5;241m1[39m, edgecolor[38;5;241m=[39m[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m, facecolor[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs):

File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/v2.py:196[0m, in [0;36mimwrite[0;34m(uri, im, format, **kwargs)[0m
[1;32m    193[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mImage must be 2D (grayscale, RGB, or RGBA).[39m[38;5;124m"[39m)
[1;32m    195[0m [38;5;28;01mwith[39;00m imopen(uri, [38;5;124m"[39m[38;5;124mwi[39m[38;5;124m"[39m, plugin[38;5;241m=[39m[38;5;28mformat[39m) [38;5;28;01mas[39;00m file:
[0;32m--> 196[0m     [38;5;28;01mreturn[39;00m [43mfile[49m[38;5;241;43m.[39;49m[43mwrite[49m[43m([49m[43mim[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py:169[0m, in [0;36mLegacyPlugin.write[0;34m(self, image, **kwargs)[0m
[1;32m    152[0m [38;5;28;01mdef[39;00m [38;5;21mwrite[39m([38;5;28mself[39m, image, [38;5;241m*[39m[38;5;241m*[39mkwargs) [38;5;241m-[39m[38;5;241m>[39m Optional[[38;5;28mbytes[39m]:
[1;32m    153[0m     [38;5;124;03m"""[39;00m
[1;32m    154[0m [38;5;124;03m    Write an ndimage to the URI specified in path.[39;00m
[1;32m    155[0m 
[0;32m   (...)[0m
[1;32m    167[0m [38;5;124;03m        particular format.[39;00m
[1;32m    168[0m [38;5;124;03m    """[39;00m
[0;32m--> 169[0m     [38;5;28;01mwith[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mlegacy_get_writer[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m [38;5;28;01mas[39;00m writer:
[1;32m    170[0m         [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_request[38;5;241m.[39mmode[38;5;241m.[39mimage_mode [38;5;129;01min[39;00m [38;5;124m"[39m[38;5;124miv[39m[38;5;124m"[39m:
[1;32m    171[0m             writer[38;5;241m.[39mappend_data(image)

File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py:150[0m, in [0;36mLegacyPlugin.legacy_get_writer[0;34m(self, **kwargs)[0m
[1;32m    148[0m [38;5;66;03m# Note: this will break thread-safety[39;00m
[1;32m    149[0m [38;5;28mself[39m[38;5;241m.[39m_request[38;5;241m.[39m_kwargs [38;5;241m=[39m kwargs
[0;32m--> 150[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_format[49m[38;5;241;43m.[39;49m[43mget_writer[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_request[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/core/format.py:204[0m, in [0;36mFormat.get_writer[0;34m(self, request)[0m
[1;32m    200[0m [38;5;28;01mif[39;00m select_mode [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mmodes:
[1;32m    201[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[1;32m    202[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mFormat [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mname[38;5;132;01m}[39;00m[38;5;124m cannot write in [39m[38;5;132;01m{[39;00mrequest[38;5;241m.[39mmode[38;5;241m.[39mimage_mode[38;5;132;01m}[39;00m[38;5;124m mode[39m[38;5;124m"[39m
[1;32m    203[0m     )
[0;32m--> 204[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mWriter[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/core/format.py:281[0m, in [0;36mFormat._BaseReaderWriter.__init__[0;34m(self, format, request)[0m
[1;32m    279[0m [38;5;28mself[39m[38;5;241m.[39m_request [38;5;241m=[39m request
[1;32m    280[0m [38;5;66;03m# Open the reader/writer[39;00m
[0;32m--> 281[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mkwargs[49m[38;5;241;43m.[39;49m[43mcopy[49m[43m([49m[43m)[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/imageio/plugins/tifffile.py:495[0m, in [0;36mTiffFormat.Writer._open[0;34m(self, bigtiff, byteorder, software)[0m
[1;32m    491[0m     [38;5;28mself[39m[38;5;241m.[39m_software [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    492[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m    493[0m     [38;5;66;03m# In tifffile >= 0.15, the `software` arg is passed to[39;00m
[1;32m    494[0m     [38;5;66;03m# TiffWriter.save[39;00m
[0;32m--> 495[0m     [38;5;28mself[39m[38;5;241m.[39m_tf [38;5;241m=[39m [43m_tifffile[49m[38;5;241;43m.[39;49m[43mTiffWriter[49m[43m([49m
[1;32m    496[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43mget_file[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mbigtiff[49m[43m,[49m[43m [49m[43mbyteorder[49m
[1;32m    497[0m [43m    [49m[43m)[49m
[1;32m    498[0m     [38;5;28mself[39m[38;5;241m.[39m_software [38;5;241m=[39m software
[1;32m    500[0m [38;5;28mself[39m[38;5;241m.[39m_meta [38;5;241m=[39m {}

[0;31mTypeError[0m: TiffWriter.__init__() takes 2 positional arguments but 4 were given
TypeError: TiffWriter.__init__() takes 2 positional arguments but 4 were given

